//! Differential tests against Jupyter's own writer.
//!
//! The fixtures under `tests/fixtures/` are generated by real Python:
//! `nbformat.write` for the notebooks, `repr(float)` for the number corpus.
//! Regenerate with `tools/gen_notebook_fixtures.py`.
//!
//! These are the tests that make the round-trip claim in
//! `crates/h5i-db-notebook/src/document/mod.rs` mean something. Asserting
//! against a fixture we wrote by hand would only prove we are self-consistent.

// The crate this exercises is Unix only; see its lib.rs.
#![cfg(unix)]

use std::path::{Path, PathBuf};

use h5i_db_notebook::Notebook;
use h5i_db_notebook::document::json::format_f64_python;

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

#[test]
fn every_nbformat_written_notebook_rewrites_byte_identically() {
    let dir = fixtures().join("canonical");
    let mut checked = 0;
    for entry in std::fs::read_dir(&dir).expect("fixture directory is missing") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("ipynb") {
            continue;
        }
        let original = std::fs::read_to_string(&path).unwrap();
        let nb = Notebook::from_json_str(&original, &path.display().to_string())
            .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let rewritten = nb.to_json_string().unwrap();
        if rewritten != original {
            panic!(
                "{} did not round-trip.\n--- first difference ---\n{}",
                path.display(),
                first_difference(&original, &rewritten)
            );
        }
        checked += 1;
    }
    assert!(
        checked >= 6,
        "only {checked} fixtures ran; expected the full set"
    );
}

#[test]
fn float_formatting_matches_python_repr_exactly() {
    let corpus = std::fs::read_to_string(fixtures().join("float_repr.txt")).unwrap();
    let mut checked = 0usize;
    let mut mismatches = Vec::new();
    for line in corpus.lines() {
        let (bits, expected) = line.split_once('\t').expect("corpus line is bits<TAB>repr");
        let value = f64::from_bits(u64::from_str_radix(bits, 16).unwrap());
        let got = format_f64_python(value);
        if got != expected {
            mismatches.push(format!("bits {bits}: python {expected}, ours {got}"));
        }
        checked += 1;
    }
    assert!(checked >= 6000, "corpus was truncated: {checked} values");
    assert!(
        mismatches.is_empty(),
        "{} of {checked} floats differ from Python:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// A readable pointer at where two renderings diverge, since diffing two
/// thousand-line JSON blobs by eye is not a debugging strategy.
fn first_difference(a: &str, b: &str) -> String {
    for (i, (la, lb)) in a.lines().zip(b.lines()).enumerate() {
        if la != lb {
            return format!("line {}:\n  expected: {la:?}\n  got:      {lb:?}", i + 1);
        }
    }
    format!(
        "identical for {} lines, then length differs ({} vs {} lines)",
        a.lines().count().min(b.lines().count()),
        a.lines().count(),
        b.lines().count()
    )
}
